export default {
        header: {
            slogan: 'Start Your Encrypted Life On NetCloth',
            home: 'Home',
            faq: "FAQ",
            chain: 'NetCloth Chain'
        }

        ,footer: {
            privacy: "Privacy Policy",
            TermsOfService: "Terms of Service",
        }

        ,landingPage: {
            ios: "iOS",
            android: "Android",
        }

        ,wish: {
            vision: "NetCloth APP’s Vision",
            title1: "A Web3.0 Portal",
            msg1:"NetCloth, a portal integrating search engines, communications, communities, DApps, and asset tools.In the future, you only need to download the NetCloth APP to experience various services that can cover the mobile Internet.",
            title2: "Information Security",
            msg2:"NetCloth protects the security of your personal information through technical solutions. Personal data generated by browsing any APPs in the NetCloth ecosystem will be encrypted and stored locally. APPs are unable to obtain your personal data without authorization.",
            title3: "Unified Encrypted Identity",
            msg3:"NetCloth uses an offline random method to generate encrypted accounts, and the encrypted identity is common in all application account systems. NetCloth's encrypted identity is natively compatible with more than 90% of the digital asset wallet systems,  enabling the integrated combination of identity + asset.",
        }

        ,personnet: {
            slogan: "Personal Network, Aggregate Your Private Traffic",
            desc1: 'Personal Network is an Internet relational network initiated and controlled by you. Each user and its associated users are a small network, which is a new network structure of Web3.0.',
            desc2: "NetCloth is committed to enabling everyone to build their own personal network, which is not only a recommended collection of portals, but also a aggregation portal  of your private traffic."
        }

        ,databox: {
            slogan: "Data Box, Create Your Data Value",
            desc1: 'Data Box is a secure personal data management tool, and users have full ownership of the data.',
            desc2: "Uers can acquire, view, modify, and authorize the data generated when browsing personal networks.Cooperate with scenarios such as Trusted Computing, and Data Exchange to protect your intangible assets and enjoy the value of your data."
        }

        ,chat: {
            slogan: "Secure Communication，Free To Travel The World",
            desc1:"Chat with friends anytime,anywhere.Support for sending voice, photos, GIF and emoji.",
            desc2: "All chat records, access data, contacts and other data are encrypted and decrypted by the user's asymmetric key."
        }

        ,wallet: {
            slogan: "One Wallet, Easily Manage Multi-Chain Assets",
            desc1: "Support one account to manage multiple blockchain assets BTC,ETH,NCH,BCH.Provide secure asset management for global users.",
            desc2: 'Ensure that assets are 100% controlled by users themselves.'
        }

        ,about: {
            business: "Business Cooperation",
            businessDesc: "Media Cooperation, Deploy Nodes, Technical Support, etc.",

            customServer: "Customer Service",
            customServerDesc: "Use Problems, Suggestions, etc.",

            officialGroup: "Join Our Community",
        }

}